apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hpvg2sgta-nodejs
  janus-idp.io/tekton: hpvg2sgta-nodejs
  backstage.io/kubernetes-id: hpvg2sgta-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpvg2sgta-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
